name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: product-catalog-service
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Configure Docker to use gcloud credentials
      run: |
        gcloud auth configure-docker
        
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        
    - name: Push Docker image to Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        
    - name: Check for existing service
      id: check-service
      run: |
        set +e
        gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format="none"
        if [ $? -eq 0 ]; then
          echo "Service exists, updating..."
          echo "service_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Service doesn't exist, creating new service..."
          echo "service_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: product-catalog-service
        image: gcr.io/product-catalog-457215/product-catalog-service:${{ github.sha }}
        region: us-central1
        flags: '--service-account=github-actions-service-account@product-catalog-457215.iam.gserviceaccount.com'
        
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}